# Generated by Django 4.2.8 on 2024-11-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_cryptocurrency'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='close_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='high_of_day',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
