# Generated by Django 4.2.8 on 2024-11-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_cryptocurrency_close_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='close_price',
            field=models.FloatField(default=0.0),
        ),
    ]
