# Generated by Django 4.2.8 on 2024-11-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_cryptocurrency_close_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='price_change_10min',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='price_change_5min',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='relative_volume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='volume_10min',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='volume_5min',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='close_price',
            field=models.FloatField(),
        ),
    ]
