# Generated by Django 4.2.8 on 2024-12-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_cryptocurrency_change_24h_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='change_24h',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='close_price',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='high_of_day',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='supply',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='volume_10min',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='volume_24h',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='volume_5min',
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='circulating_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='gap_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='price_change_24hr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='volume_24hr',
            field=models.FloatField(default=0.0),
        ),
    ]
